### ISSUE TITLE
Improve signup and login experience

### ISSUE THREAD

**Issue by Adam3371** [corbado/example-passkeys-flutter#32]
# Scope
Design drafts can be found in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=7274%3A2&mode=design&t=I9aWED3n6v83o2hm-1)

# TODO:

- [ ] For the login/signup page, add a frontend validation to check if an email is entered in the email field and a the name field is not empty. Otherwise trow an error shown in in Figma Screen E1.0.0, E2.0.0, E2.0.1.
- [ ] If at login/signup a error is thrown from the BE, show the according message below the input field. Error messages can be found in the Figma E1.0.1
- [ ] Improve the OTP input flow:
   - It should be possible to click in the input field and past the whole code
   - When pasted the code or manually entered the code, the cursor should be at the last input field and deleting should be easy.
   - If a wrong code is enter, the error message shown in Figma screen E1.1.0 should be shown, the input field should appear red and the code should be deleted. The cursor should be placed at the first input field and when entering the first digit, the error state should disappear. 
- [ ] When clicking on the login/signup button, check if there is a internet connection. If there is not, a "No internet" error banner should pop up. The banner is shown in the Figma screen E1.0.1.
- [ ] When clicking on the login/signup button, check if there is any problem with the connection to the BE. If there is, a "Something went wrong" error banner should pop up. The banner is shown in the Figma screen E1.0.2.
- [ ] For every action on the app that requires the BE, check if there is internet connection and otherwise show the "no internet" error banner. (Check with Adam, if task is time consuming).

iOS
- [ ] Refactor the Login screen for iOS according to the Figma screens S1.0.0. Don't make a link out of the "corbado.com" text.
- [ ] When clicking in the email input field, a "Choose account" card should appear from the bottom. (Similar to the current android implementation. P1.0.1)

Android
- [ ] Refactor the login and sing up screens for iOS and Android according to the Figma screens S2.0.0 and S2.0.1.
- [ ] When entering the OTP on android, don't allow other symbols than numbers on the android "keyboard" (P2.1.1). (Only if can be done quickly)
