### ISSUE TITLE
Improve passkey list

### ISSUE THREAD

**Issue by Adam3371** [corbado/example-passkeys-flutter#33]
# Scope
Design drafts can be found in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=7274%3A2&mode=design&t=I9aWED3n6v83o2hm-1)
# TODO
- [ ] Refactor the Passkey list according to the Figma screens S1.7.0. 
- [ ] Depending where the passkey was created, show the according:
    - Icon
    - Keychain/Authenticator/Password Manager 
    - OS and Environment where it was created
    - Creation date-time
    - Last use date-time
    - Credential ID
    - Synced or Not Synced
    - (A passkey fallback in case information could not be extracted
- [ ] Add the possibility to append additional passkeys. If an error is thrown, error message and style should be according to Figma E1.7.0.
- [ ] Add the possibility to delete passkeys by clicking on the bin of the corresponding passkey. When clicking, open a delete dialog on the bottom (like already implemented).
